public class CRM_IntegrationConstants {
    
    public final static String INTEGRATION_RESPONSABLE = 'OCResponsable';
    public final static String INTEGRATION_RESPONSABLE_DATA_PARAM = 'Data';
    public final static String INTEGRATION_RESPONSABLE_BODY_TEMPLATE = 'username=salesforce&password=CWKwfX7SbWqVjs6V&data={"activo":"true","nombre":"Jorge","apellido1":"Sabido"}';
    //public final static String INTEGRATION_RESPONSABLE_BODY_TEMPLATE = 'username={0}&password={1}&data={"activo":"true",{2}}';

}