public class CRM_IntegrationConstants {
    
    //INTEGRACION BUSQUEDA CODIGO RESPONSABLE
    public final static String INTEGRATION_RESPONSABLE_NAME = 'OCResponsable';
    public final static String INTEGRATION_RESPONSABLE_PARAM01 = 'Data';
    public final static String INTEGRATION_RESPONSABLE_BODY_TEMPLATE = 'username=salesforce&password=CWKwfX7SbWqVjs6V&data={"activo":"true","nombre":"Jorge","apellido1":"Sabido"}';
    
    
    //INTEGRACION APROBACIONES
    public final static String INTEGRATION_APR_PRELIMINAR_NAME = 'AprPreliminar';
    public final static String INTEGRATION_APR_PRELIMINAR_PARAM01 = 'tareaID';
    
}